apiVersion: v1
kind: Service
metadata:
  name: cirkelline-backend
  namespace: cirkelline
  labels:
    app: cirkelline-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "7777"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 7777
      protocol: TCP
  selector:
    app: cirkelline-backend
---
apiVersion: v1
kind: Service
metadata:
  name: cirkelline-backend-headless
  namespace: cirkelline
  labels:
    app: cirkelline-backend
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 7777
      targetPort: 7777
  selector:
    app: cirkelline-backend
